name: Build Application Archive
# This action builds the application archive and uploads the artifact to Github.

on:
  workflow_dispatch:

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      -
        run: echo ${{ github.repository }}
      -
        run: mkdir pkg
      -
        run: docker run -e REPO_NAME=${{ github.repository }} -v ${{ github.workspace }}/pkg:/build/pkg tbeauvais/archive-builder:latest
      -
        name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: application-artifact
          path: ${{ github.workspace }}/pkg
