name: Build Application Archive
# This action builds the application archive and uploads the artifact to Github.

on:
  workflow_dispatch:
    inputs:
      archive_name:
        description: 'The archive name. This must be a valid file prefix.'
        required: true
        default: 'test_app'
      version_level:
        description: 'The semantic level for the version bump'
        type: choice
        options:
          - patch
          - minor
          - major
        required: true
        default: 'patch'

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Bump Version
        run: |
          VERSION=$(bundle exec rake version:bump:${{ inputs.version_level }})
          echo $VERSION
      -
        run: mkdir pkg
      -
        run: docker run -e ARCHIVE_NAME=${{ inputs.archive_name }} -e BRANCH_NAME=${{ github.ref_name }} -e REPO_NAME=${{ github.repository }} -v ${{ github.workspace }}/pkg:/build/pkg tbeauvais/archive-builder:latest
      -
        name: Release Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: $VERSION
          artifacts: "${{ github.workspace }}/pkg/*.zip"
