name: Create Build Archive Container
# This action builds the image for running the application archiver in Docker, and pushes it to Docker Hub.

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./DockerBuildFile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/archive-builder:latest
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Image used to build application archive.
